version: '3.9'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: python manage.py runserver_plus --cert-file cert.crt 0.0.0.0:8000
    volumes:
      - .:/code 
    environment:
      - "DJANGO_SECRET_KEY=pHC8vSCUb3stP8gwfwgUfrdBvXBuis3HkAxl_IsWoBGHJDYcWug"
      - "EMAIL_HOST_USER=rogeliofirmino20@gmail.com"
      - "EMAIL_HOST_PASWORD=emilio2404"
  db:
    image: postgres:15
    volumes:
      - ../data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=dj_bookstore
    ports:
      - "5432:5432"

volumes:
  pg_data: