# Generated by Django 4.2.7 on 2023-12-03 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('especial_status', 'Can read all books')]},
        ),
    ]
